### ISSUE TITLE
integrate robocop with visual studio code linting

### ISSUE THREAD

**Issue by eldaduzman** [MarketSquare/robotframework-robocop#200]
**Is your feature request related to a problem? Please describe.**
It would be awesome to have robocop operate just like any python linters in visual studio code (mypy, pylint, flake8 etc).

**Describe the solution you'd like**
a visual studio code extension that will have similar fields to python linters (enabled, lint on save)

**Comment by bhirsz** [comment]
We definitely plan to support most popular IDEs. That's why issues like #168 are in our plans. The problem of course is that every IDE have very different way of working with such tools. That being said I took a look into Visual Studio Code and it looks quite promising. 

This article https://code.visualstudio.com/docs/python/linting describes how to use python linters. The fastest way to get Robocop running with VS Code would be mimicking Robocop as other linter (configure path to executable for given linter ie pylint to robocop instead). Of course it would be better to add Robocop as official linter to VS Code. 

I will investigate what we need to do in order to get it done.

**Comment by bhirsz** [comment]
Found this resource from LSP: https://microsoft.github.io/language-server-protocol/specification under "Diagnostic". We could generate diagnostic information in LSP server - it would be most versatile as it would also support other IDEs

**Comment by eldaduzman** [comment]
Thanks @bhirsz, I'll read the links you sent me.

**Comment by bhirsz** [comment]
We're currently working on integration with Robot Framework LSP which make it possible to integrate Robocop into most popular IDEs. Here is post regarding Intellij: https://github.com/MarketSquare/robotframework-robocop/issues/221#issuecomment-805032121 but it should work even better for Visual Studio Code since it supports LSP natively (check out https://github.com/robocorp/robotframework-lsp for more details).

**Comment by bhirsz** [comment]
Closing this issue because Robocop is already integrated to LSP through https://github.com/robocorp/robotframework-lsp and should be available in PyCharm and Visual Studio Code. Note that it's best to install most recent version of Robocop globally (and update it frequently) because LSP is shipped with old version of Robocop that don't have recent fixes.
