### ISSUE TITLE
Special charachter in keywords make W0302 fail

### ISSUE THREAD

**Issue by denagyantal** [MarketSquare/robotframework-robocop#248]
This keyword makes the W0302 fail even though the keyword is capitalized: 
`Edit Group's Report Logo`

The only solution we found to avoid this is the following:
`Edit Group's Report Logo    # robocop: disable`

Is it possible to treat "Group's" as one word or refactor is the only option?

Our use case is special, we are using the report.html for official reporting for the authorities and it is easier to use special characters like this.

**Comment by bhirsz** [comment]
I believe its bug - it should strip any non letter char before making check. I will verify it

**Comment by bhirsz** [comment]
I made straightforward fix in https://github.com/MarketSquare/robotframework-robocop/commit/7325c3af599b4690429cd0f5942066d39ed4223d and I'm going to release robocop == 1.3.2. 

This rule will be reworked right after I finish major tasks in my other tool (robotidy) because I'm not happy how it growed over time & I would also want to be able to catch embedded value ('Keyword With ${var} == Keyword With 5). But it will mostly affect internal implementation and not what issues this rule catch.
