### ISSUE TITLE
Loosen check of capitalization of keyword names optionally

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-robocop#359]
**Problem**
Rule 0302 checks whether every word of a keyword name starts with capital letter. This is too strict for two reasons:

- For other languages than English might be natural to name things with only the first letter of their name being capital.
- Even in the (English) [documentation](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html) of RF, we can find many keywords with only the first letter of their names being capital. 

**Suggestion**
I'd like the rule 0302 to be configurable: the default value of its parametr would check for every first letter being capital, as it does up to now. When the other value of the parameter will be specified, check for first letter of the first word only would be performed.

**Comment by mnojek** [comment]
Thanks @MoreFamed for your request.

First of all, even if the official documentation contains keywords that do not have all words capitalized, it is advised to follow such convention. Such examples are rather overlooked.
Secondly, in Polish, for example, we use only capital letter at the beginning of the sentence, but since keyword names are not sentences and it is a programming language with some specific syntax and conventions, it's OK to make all words in a keyword capitalized, in my opinion. It shouldn't be dependent on any language - it's just a convention of Robot Framework language.
Moreover, people responsible for Robot Framework development say that this practice should be default and I agree with them.

Linters are the tools that need to enforce some rules and thanks to this, the code is more consistent and easy to read. The only option I can see here is that we can provide a configurable parameter that can enable user to choose if he/she wants to use all words capitalized, or only the first one, but I still need to think if this is the way we want to go.

**Comment by MoreFamed** [comment]
@mnojek, thank you for your reaction. I understand your point of view, however, I'd like to add some notes.

First of all, I missed to stress that we do write our own keywords in Czech (and I guess rules or conventions of capitalization in Czech are very similar to that ones in Polish). In Czech, there is natural to name things "Like this", not "Like This". In other words, Names Like This, when written in Czech, make reading a script harder.

And that is connected with my second remark. Language of RF has been designed to mimic natural language to a vast extent. This is why, for example, it allows spaces and letters with diacritics to be in names of entities---unlike usual programming languages. It would be natural, in my opinion, to allow even capitalization of names be decided by conventions of the natural language names are written in and Robocop should check the compliance with this convention...

Please, let me know when you decide about this issue.

**Comment by bhirsz** [comment]
I agree that we could add flag for this rule allowing to 'loosen' check only for first word. For example ``check_only_first_word`` or similar.
