### ISSUE TITLE
Detect if tag was forced in some higher init

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-robocop#379]
Currently rule 0606 detects only if tag was forced within the same suite but it does not detect if tag was already forced in some higher init file. 
It would be useful to have such rule, maybe as separate rule.

**Comment by mnojek** [comment]
Thanks @adrszad for this request but unfortunately we are not going to implement since it needs the whole tool to start reading the context and remembering the hierarchy of the files which is out of scope of this simple tool which just statically reads file and analyzes it. Maybe such feature can be implemented in https://github.com/robocorp/robotframework-lsp. You can try request it there or check earlier if it's not already on their schedule.
Please @bhirsz close the ticket if you agree with me.
