### ISSUE TITLE
[Rule] Duplicated variable across project

### ISSUE THREAD

**Issue by fdaguin** [MarketSquare/robotframework-robocop#399]
**Is your feature request related to a problem? Please describe.**

See:

- [ ] robotframework/robotframework#2970 

**Describe the solution you'd like**

I'd like a new Robocop rule to be created which will detect if any variables share the same name across all the resource files of a project. The variables to be *audited* will be the ones either defined:

- through variable files
- inline, under a `*** Variables ***` section

**Additional context**

This is an extension of **E0803** where a `duplicated-variable` is already detected.

A possible recommandation might be like #398 where using a prefix is advised.

**Comment by mnojek** [comment]
Hi @fdaguin and thanks for the issue. Unfortunately, this will not be implemented because it requires significant changes to the tool that are not in the scope of it. We would need to read the context and understand the variables across all the places while Robocop only parses and analyses one file at a time. I need to close this issue. You can ask for this feature our friends from https://github.com/robocorp/robotframework-lsp project. It fits better there. Have a nice testing!

**Comment by fdaguin** [comment]
Alright, thank you for your response @mnojek 😃
