### ISSUE TITLE
Check variable names for RF's recommendation

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-robocop#502]
[RF's documentation](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-variables) reads:
_Variable names can basically have any characters between the curly braces. However, using only alphabetic characters from a to z, numbers, underscore and space is recommended, and it is even a requirement for using the extended variable syntax._
This is why I suggest to create a rule for checking it: variable name should match `[a-zA-Z0-9_ ]+` 

Note: rule _hyphen-in-variable-name_ could be deleted, rules checking upper/lowercase in variable names could be left untouched.

**Comment by mnojek** [comment]
Since RF has support for multiple languages, I would not introduce a rule that checks whether a variable name contains only characters from range `[a-zA-Z0-9_ ]+`. Also, we already have mentioned `hyphen-in-variable-name` rule, which I think is beneficial, because it detects cases where "hyphen" may be recognized as minus sign.

The only place where I can see a new rule is to detect if the name conforms to the extended variable syntax requirements, as mentioned above.

@bhirsz What do you think? Do we want such a rule? And what do you think about what I wrote here?

**Comment by mnojek** [comment]
Agreed. I will close this one then and put it into the #809 task about the community rules.
