### ISSUE TITLE
Don't suggest new IF-block for the only keyword (optionally)

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-robocop#506]
I do like new IF ... ELSE IF ... END much; however, look at my example.  
```
Run Keyword If  ${DEBUG}  Log  We are here
```
vs.
```
IF  ${DEBUG}  
    Log  We are here
END
```
The first form is shorter, at least when considering number of lines, and it does not deter junior users by using something else than keywords. :) I would rather like Robocop not to suggest me that such a construction can be replaced with IF block. But the only option is now to turn off the rule completely. 

This is why I suggest to turn off the message of rule _if-can-be-used_ optionally (by means of a parametr) in case of a single-line conditional statement using _Run Keyword If/Unless_. In other words: ... in case when there is no ELSE/ELSE IF-branch and there is no _Run Keywords_ as the argument.

Note below: I am leaving for holidays and will be back and ready for discussions with you on 4th of October. 😃

**Comment by bhirsz** [comment]
I agree that there isn't much benefit of using IF block in your example. Hovewer I often saw something like this:
```
Run Keyword If  ${DEBUG}  Log  We are here
Run Keyword If  ${DEBUG}  Log  Something else
Run Keyword If  ${DEBUG}  Log  And even third keyword in a row
```
We don't have else/else-if branch here but it would be still better to use one IF. But since it would be optional mode for if-can-be-used rule I think we can accept this. We could add flag "ignore_single_statement" or something similar.

Just a note that Robot Framework 5.0 will most likely allow to define IF in one line (without END) so it will somehow allieviate this issue.

**Comment by MoreFamed** [comment]
You are right. So I suggest postponing the issue till RF 5.0 is released: if it will implement IF-oneliners, we can close this.

**Comment by bhirsz** [comment]
Closing the issue since upcoming RF 5.0 introduced IF-oneliners ;)
