### ISSUE TITLE
Tag rules for another RF version in --list

### ISSUE THREAD

**Issue by mnojek** [MarketSquare/robotframework-robocop#507]
Currently, `--list` option shows all possible rules whether they are compatible with current local RF version or not. Would be nice to have some tag that will show which rules will be turned off by default due to different RF version.
We can do it either next to these rules, like this (assume that we have RF 3.2.*):
```
(...)
Rule - 0907 [E]: nested-for-loop: Nested for loops are not supported. You can use keyword with for loop instead (enabled for RF 4.*)
Rule - 0908 [I]: if-can-be-used: '%s' can be replaced with IF block since Robot Framework 4.0 (enabled for RF 4.*)
(...)
```
or just list them at the bottom of the list:
```
(...)

Rules disabled due to different Robot Framework version:
Rule - 0907 [E]: nested-for-loop: Nested for loops are not supported. You can use keyword with for loop instead (enabled for RF 4.*)
Rule - 0908 [I]: if-can-be-used: '%s' can be replaced with IF block since Robot Framework 4.0 (enabled for RF 4.*)
```

**Side note**: We need to add it also to the docs.

**Comment by bhirsz** [comment]
I think listing it next to rule is better - we have lots of rules so listing it separetly would overclutter output. We can add this information only if the rule is not supporting all version (ie only for 3.2.2, only for >=4.*). 

Related #470 because it would be easier to implement this issue if we have better handling of versions.

It's up to discussion where to store this information - maybe it would be best to add it to rule definition? It would be then always visible when modyfing the rule, we could add in-built methods for delaying with version support (ie exclude not supported rule automatically) and our auto-generated docs could read from there. Example:

```
        "0908": (
            "if-can-be-used",
            "'%s' can be replaced with IF block since Robot Framework 4.0",
            RuleSeverity.INFO,
            ">=4.0"
        )
```

But then the discussion if the rule itself should be class comes back.

**Comment by mnojek** [comment]
I think that it's high time to finally rewrite the rules into classes and we will solve several issue with this decision :) Maybe I will find tomorrow to start this work.
