### ISSUE TITLE
Complexity metrics for robot code 

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-robocop#537]
I'd like to see some complexity metrics for Robot Framework code. Actually some of the current rules for lengths are kind of complexity checkers, but it would be good to have more advanced metrics, like e.g. in this library:
https://radon.readthedocs.io/en/latest/

**Comment by bhirsz** [comment]
I will close this issue for now but with good intent: we have it on our roadmap and we're working on it. It will be implemented by another tool (it was easier to create another tool for such tests because of the support of reading both from sources and xml outputs). Most likely we will allow some kind of integration (ie robocop could start and collect issues from other tool). I will ping you in this issue once there will be first release ;)
