### ISSUE TITLE
Add Rules that required to keyword used at least once ( AKA find unused keywords) 

### ISSUE THREAD

**Issue by IlfirinPL** [MarketSquare/robotframework-robocop#608]
Add Rules that required to keyword used at least once ( AKA find unused keywords) 
I see additional options 

* only validate rule for Tests/Tasks with "Tag" or exclude with tags ex. TODO
* set minimum used ( example show keywords used less than X times)

**Comment by mnojek** [comment]
Hey @IlfirinPL and thanks for the suggestions. Unfortunately, Robocop is not able and will not be able to do such things. This is a simple tool that reads the code without understanding the context - it parses one file at a time, checks if it violates the rules and then returns messages. It does not know what is inside the next file until it finishes the current one, and when it's done, it's suddenly forgotten.

The new tool that is being developed by @bhirsz is able to understand the context and count keywords by usage and show statistics (it also has many other cool features). Check it out [here](https://github.com/bhirsz/robotframework-sherlock).

I am closing this issue, because it won't be implemented.

**Comment by IlfirinPL** [comment]
Thank you for information I will check Sherlock
