### ISSUE TITLE
[Bug] 2.1.0 Version string not updated on documentation image

### ISSUE THREAD

**Issue by rikerfi** [MarketSquare/robotframework-robocop#620]
### What happened?

https://robocop.readthedocs.io/en/stable/index.html#
Robocop image still states `2.0.2` version at top-left corner.

### Robocop version

2.1.0

**Comment by bhirsz** [comment]
Thanks for noticing. I will investigate - I see the doc did build successfully (https://robocop.readthedocs.io/en/2.1.0/reports.html is showing new report for example), it just that the versions on the page did not update.

**Comment by bhirsz** [comment]
I also see similar case in Robotidy (here it didn't trigger at all)

**Comment by bhirsz** [comment]
Robotidy - outdated webhook, fixed it. 
Robocop - most likely it's because I've created release (and created tag 2.1.0 in git) and forgot to update version in version.py. I did fix it yesterday and released but tag is still pointing to the code that don't have proper version set.. . I will try to update the tag and see if it helps.

**Comment by bhirsz** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/8532066/174291408-115bf045-7d0c-44d1-b20b-f84909281714.png)

It was actually fun to see how things are working 'under the hood' (I did setup that but that was long ago and part of it was magic ;) ). Closing the issue.
