### ISSUE TITLE
[Bug] Rule missing-space-after-comment complaining of too much `#`s

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-robocop#634]
### What happened?

The rule 0702 complains that a `#` char that is in a comment but is not the first char of the comment (i.e. it does not turn the rest of the line into a comment) is not followed by a space. 
![image](https://user-images.githubusercontent.com/82573620/178728634-2fc1294d-560f-472c-829c-1ebb15802bf9.png)
This is either a bug or at least an inconsistency: Robocop should complain of the rest of `#`s as well. (But I will rather see this as a bug. 😄)

### Robocop version

2.0.2

**Comment by bhirsz** [comment]
Bug:
1) it should check for blank space after `#` only at the beginning of the comment 
2) For multiple `###..` it maybe should just skip it anyway 

The bug happened because you actually have two comments here - if there is more than two spaces in a line with comment, Robot Framework parses it as: COMMENT, SEPARATOR, COMMENT. We should add extra handling there and 'merge' it as single comment before checking for comment validity.
