### ISSUE TITLE
More not-capitalized-test-case-title (0308) options

### ISSUE THREAD

**Issue by KUGA2** [MarketSquare/robotframework-robocop#666]
Rule [0308](https://robocop.readthedocs.io/en/stable/rules.html#not-capitalized-test-case-title) should also check for: each word capitalized, like rule 0302 ([wrong-case-in-keyword-name](https://robocop.readthedocs.io/en/stable/rules.html#wrong-case-in-keyword-name)) does.

(for stability reasons, this could be a new rule with new id)

**Comment by mnojek** [comment]
Hey @KUGA2, thanks for your suggestion, and sorry for long delay.

I revisited this issue and I think it should not make its way to the core Robocop rules, because there is no such recommendation in the official RF User Guide, and also I would leave it up to the users to decide how they want to name the test cases.

For example, I can imagine a test case which name can be written in different ways:
```
Verify if the page contains an image
Verify If the Page Contains an Image
Verify If The Page Contains An Image
```
and it should be left up to the user which one is better. Each team/organization/project may have different requirements and different people involved in adding or reading the test cases, and the only rule that probably everyone agrees with is that the test case should start with a capital letter. All the rest is not something strict, and may vary between different cases.

That's why I am closing this issue for now, but I have added the rule idea as a candidate for the community rule in #809 (which may come true soon).

You may of course still share your opinion about it here 🙂

**Comment by bhirsz** [comment]
And if you need it, Robotidy has RenameTestCases transformer that can be configured to capitalize each word: https://robotidy.readthedocs.io/en/stable/transformers/RenameTestCases.html
