### ISSUE TITLE
Add pre-commit hook file

### ISSUE THREAD

**Issue by bhirsz** [MarketSquare/robotframework-robocop#752]

**Comment by bhirsz** [comment]
Feel free to ask if you have any other questions or there is some issue when configuring the pre commit!

**Comment by OrrinGradwell** [comment]
Thank you very much.

I will play with this and then get back to you should I have any issues!

Thank you once again for such fast response!

**Comment by OrrinGradwell** [comment]
Morning.

Quick update!
This is work beautifully! 

Thanks for jumping on this so quickly!
You guys are legends!

**Comment by OrrinGradwell** [comment]
Hi @bhirsz 

I am revisiting this and seeing that tag 2.6.0 is now availible, I tried to change my pre-commit to reflect this instead of the `master` revision as it currently does.

As sson as I make the change, then i get the following response:

$ pre-commit run
An error has occurred: InvalidManifestError: 
=====> /home/orrin/.cache/pre-commit/repo6c7tk2ec/.pre-commit-hooks.yaml is not a file

Switching back the rev to "master" does allow me tor un the "pre-commit run" command again.

Am I missing something or should I create a bug for you guys :)

Have a good one!

@OrrinGradwell
