### ISSUE TITLE
[Bug] inline-if vs. inline-if cannot contain assignments

### ISSUE THREAD

**Issue by loumaran** [MarketSquare/robotframework-robocop#817]
### What happened?

I got the issue `[I] 0916 IF can be replaced with inline IF inline-if-can-be-used`.
After using an inline-if, the next issue occured: `[E] 0413 Invalid IF syntax: Inline IF branches cannot contain assignments invalid-if`.

### What command/code did you try to run?

```
IF    '${sudo}'=='${True}'
        ${sudo_cmd} =    Set Variable    sudo
END
```

and

```
IF    '${sudo}'=='${True}'    ${sudo_cmd} =    Set Variable    sudo
```

### What is the full error message?

I got the issue `[I] 0916 IF can be replaced with inline IF inline-if-can-be-used`.
After using an inline-if, the next issue occured: `[E] 0413 Invalid IF syntax: Inline IF branches cannot contain assignments invalid-if`.

### What did you expect to happen instead?

I would expect, that the rule is smart enough to recognize, that an inline-if is not possible.

### Operating System

Win

### Robocop version

3.0.0

**Comment by bhirsz** [comment]
If you want achieve inline IF with assignments, you need to place it before IF:

```
 ${sudo_cmd} =    IF     '${sudo}'=='${True}'    Set Variable    sudo    ELSE    ${None}
```

However it may be better idea to use ``Set Variable If``:

```
 ${sudo_cmd} =   Set Variable If    '${sudo}'=='${True}    sudo
```

Also, you don't need to convert variables to string and compare them with their native types if you use ``$var`` syntax. It's because with ``${var}`` Robot Framework places variable value directly to Python expression and with ``$var`` as variable:

```
IF    $sudo
        ${sudo_cmd} =    Set Variable    sudo
END
# or
 ${sudo_cmd} =    IF    $sudo    Set Variable    sudo    ELSE    ${None}
```

**Comment by loumaran** [comment]
Thanks a lot! I didn't see that :)
