### ISSUE TITLE
[Bug] Deprecated-statement rule incorrectly triggered for use of [RETURN]

### ISSUE THREAD

**Issue by amandazeigler-signifyd** [MarketSquare/robotframework-robocop#956]
### What happened?

A robot keyword using the correct [RETURN] statement triggers a deprecated-statement error

### What command/code did you try to run?

`python -m robocop` on our robot test suite

### What is the full error message?

`[W] 0319 '[Return]' is deprecated since Robot Framework version 5.*, use 'RETURN' instead (deprecated-statement)`

### What did you expect to happen instead?

No error should be reported

### Operating System

Ubuntu   22.04.3   LTS

### Robocop version

robotframework-robocop-4.1.1

**Comment by bhirsz** [comment]
Are you using Robot Framework >=5? While it's not officially deprecated yet (with deprecated message) you can read here https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-return-setting that ``The [Return] setting is effectively deprecated and the RETURN statement should be used``. That's why we report this as an issue. If you get this message with RF <5 then it's indeed bug (it should be only reported from 5 onwards).

**Comment by amandazeigler-signifyd** [comment]
@bhirsz Hi, thanks for the quick reply. Yes, I am using [RETURN] in the robot file, but the rule is still firing incorrectly for some reason.

**Comment by bhirsz** [comment]
Closing as it's not an bug (and apologies for late reply): ``[Return]`` is in fact deprecated since RF 5.0 and will be removed in RF 8.0.  The syntax is still correct but could be replaced with new syntax. That's why ``deprecated-statement`` warns about it.
